// 매장 레이아웃 템플릿 샘플
export const layoutTemplates = [
  {
    id: "basic",
    name: "기본형",
    elements: [
      {
        id: "room-1",
        type: "room",
        x: 100,
        y: 100,
        width: 200,
        height: 120,
        rotation: 0,
        properties: {
          roomNumber: "A",
          roomName: "회의실",
          capacity: 6,
          pricePerHour: 20000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "room-2",
        type: "room",
        x: 350,
        y: 100,
        width: 200,
        height: 120,
        rotation: 0,
        properties: {
          roomNumber: "B",
          roomName: "오픈데스크",
          capacity: 10,
          pricePerHour: 15000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "text-1",
        type: "text",
        x: 180,
        y: 250,
        text: "카운터",
        fontSize: 20,
        fill: "#333",
      },
    ],
  },
  {
    id: "corner",
    name: "코너형",
    elements: [
      {
        id: "room-1",
        type: "room",
        x: 100,
        y: 100,
        width: 180,
        height: 100,
        rotation: 0,
        properties: {
          roomNumber: "A",
          roomName: "코너룸",
          capacity: 4,
          pricePerHour: 18000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "room-2",
        type: "room",
        x: 100,
        y: 220,
        width: 180,
        height: 100,
        rotation: 0,
        properties: {
          roomNumber: "B",
          roomName: "메인룸",
          capacity: 8,
          pricePerHour: 25000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "text-1",
        type: "text",
        x: 320,
        y: 150,
        text: "입구",
        fontSize: 18,
        fill: "#333",
      },
    ],
  },
  {
    id: "large",
    name: "대형",
    elements: [
      {
        id: "room-1",
        type: "room",
        x: 80,
        y: 80,
        width: 250,
        height: 140,
        rotation: 0,
        properties: {
          roomNumber: "A",
          roomName: "대형룸",
          capacity: 16,
          pricePerHour: 40000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "room-2",
        type: "room",
        x: 350,
        y: 80,
        width: 120,
        height: 140,
        rotation: 0,
        properties: {
          roomNumber: "B",
          roomName: "소회의실",
          capacity: 4,
          pricePerHour: 12000,
        },
        style: { fill: "#e3f2fd", stroke: "#1976d2", strokeWidth: 2 },
      },
      {
        id: "text-1",
        type: "text",
        x: 200,
        y: 250,
        text: "카운터",
        fontSize: 20,
        fill: "#333",
      },
    ],
  },
];
